### ISSUE TITLE
ASCOM driver for the WeatherLinkIP - Version ?

### ISSUE THREAD

**Issue by Stargazer32584** [blumzi/ASCOM.VantagePro#1]
Hi,

you make a great work for all the amateur-astronomers out there.
But do you plan a version for ASCOM with the WeatherLinkIP interface ?

Best regards

André

**Comment by blumzi** [comment]
Hello André and thank you for your kind words!

Unfortunately, I don't have access to a WeatherLinkIP installation.  That being said, you can use the driver in the WeatherLink operational mode, where it will parse a report generated by WeatherLink, without directly accessing the station.

Advantages:
- You'll have WeatherLink running at all times and enjoy its reporting capabilities
- There will be no contention when accessing the weather station (as far as I understand, even the IP access is one-at-a-time)
Disadvantages:
- You'll have WeatherLink running at all times (I personally find it to be a very pesky application :-)

Please let me know what you think and how can I be of assistance.

Clear sky,

**_Arie_**

**Comment by Stargazer32584** [comment]
Hi Arie,

so, if i take these option, what does he parse ?
My personal site  of our station on WeatherLink.com ?

For this function, i need to give your program the whole link. Is it right ?

The main problem is, that i don't have the WeatherLink program on my observatory PC.
The Davis vantage pro 2 is only connected via
ethernet.  

If you want design a program for WeatherLink IP stations, i could test it...

Thank you, Clear Skies and best regards

André

**Comment by blumzi** [comment]
Hi André,

I had a brief look around and found that this may not be that hard after all. I'd like to try it but it will take me a little while to get to it.

I appreciate your offer to assist with testing.  If your station is reachable from my home computer, that will help a lot.
Please use my home [address ](mailto:theblumz@gmail.com) to send me the IP address and port, I'll take it from there.
If you know of any other VantagePro with a reachable IP address, that would work as well.

Best regards,

Arie

**Comment by blumzi** [comment]
Oh, I didn't really answer to your question :-(

If you do have a PC with WeatherLink running on it
- The instructions for my driver will guide you about setting WeatherLink to create an HTML report in a .http file on the computer.  You can set the frequency, every one minute will do.
- The driver supplies an HTML template to be used by WeatherLink when creating the report
- The template just forces WeatherLink to dump all the values it maintains internally
- The driver parses the HTML contents, gets the relevant values and presents them via the ASCOM protocol.

If you feel a bit more adventurous, you could:
- Run the driver in this mode on the PC that runs WeatherLink
- Setup an ASCOM Remote Server on that PC
- Set up an Alpaca remote driver on your PC and point it to the ASCOM Remote Server
- Voila, you have it

While you're having all this fun I'll have a look at teaching my driver to connect to the VantagePro via IP (but I need access to a real station :-)

All the best,

Arie

**Comment by Stargazer32584** [comment]
Hi Arie,

thanks a lot for your help !

The Vantage Pro ist not connected to ans pc.

The data comes directly from the WeatherLink IP - Server.
But, if it is possible to read the data from the station 
in the local network, not from the WLIP-Server, this would be great !

So, do you need the local-IP and the port of the station, right ?

I will send you an e-mail on your adress in the next 6 hours.

Best wishes to you,

André

**Comment by blumzi** [comment]
Hi André,

There is a new installer in "Solution Items".  Please give it a try!

**Comment by blumzi** [comment]
Hi Andre,

I added IP support to the driver.  The new version is v1.2.  There is a new
installer in the "Solution Items" directory.
The Setup window allows you to select the "IP" mode and supply the IP
address (IPv4 only).
If you enable "Trace" in the Setup window it will show you the path to the
trace file (text log).  That will let you (hopefully) know what's going
on.  In case things don't work (expected :-), please send me the file!

Good luck,

- Arie
