### ISSUE TITLE
raw-data access issue with Python

### ISSUE THREAD

**Issue by fockez** [blumzi/ASCOM.VantagePro#2]
I use comtypes under Python to access this ASCOM driver. When I access the raw-data, I met the error of missing Newtonsoft.Json
The error message is
_ctypes.COMError: (-2147352567, '发生意外。', ('未能加载文件或程序集“Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。系统找不到指定的文件。', 'ASCOM.VantagePro.ObservingConditions', None, 0, -2147024894))
Sorry for the Chinese in the message, but I believe the main information is there.

**Comment by blumzi** [comment]
Please try the latest installer and let me know how it works.
BTW, what kind of station do you have?

Cheers,

- Arie

**Comment by fockez** [comment]
OK, I will this later. I just spend several days come back from the observatory, so I will try to install this remotely. 
The station is Vantage Pro 2 wireless with PM 2.5 sensor

**Comment by fockez** [comment]
After I installed the new one, it has some issue.

22:15:22.250 Main                      Thread exception: System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 ASCOM.VantagePro.SetupDialogForm.buttonTest_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This is what happened when I set the serial port and press test button.
